use ifschool;
CREATE TABLE std_fee(id INT PRIMARY KEY,std_id INT NOT NULL,amount INT NOT NULL,
a_status VARCHAR(200) NOT NULL,a_date DATE NOT NULL,CONSTRAINT FK_stdid FOREIGN KEY(id)
references std_details(id));

INSERT INTO STD_FEE(ID,STD_ID,AMOUNT,A_STATUS,A_DATE) VALUES(1,1,"10000","PAID","2024-10-01"),
(2,2,"12000","PENDING","2024-12-30"),(3,3,"5000","PAID","2024-12-30"),
(4,4,"5000","PENDING","2024-12-30"),(5,5,"15000","PAID","2024-12-30");

SELECT * FROM STD_FEE;
SELECT * FROM STD_DETAILS;
SELECT * FROM SUB_DETAILS;

SELECT ID,STD_NAME,STD_AGE FROM STD_DETAILS;
SELECT DISTINCT STD_AGE FROM STD_DETAILS;

SELECT ID,STD_NAME,STD_AGE 
FROM STD_DETAILS WHERE STD_GEN="M";

SELECT ID,STD_NAME,STD_AGE FROM STD_DETAILS WHERE STD_GEN="F";

SELECT ID,STD_NAME,STD_AGE FROM STD_DETAILS WHERE STD_GEN="M" AND STD_AGE=23;
SELECT ID,STD_NAME,STD_AGE FROM STD_DETAILS WHERE STD_GEN="M" OR STD_AGE=23;
SELECT ID,STD_NAME,STD_AGE FROM STD_DETAILS WHERE NOT STD_GEN="M" AND STD_AGE=23;
SELECT ID,STD_NAME,STD_AGE FROM STD_DETAILS WHERE NOT STD_GEN="M" OR STD_AGE=23;

SELECT ID,STD_NAME,STD_AGE FROM STD_DETAILS WHERE STD_NAME LIKE "A%";
SELECT ID,STD_NAME,STD_AGE FROM STD_DETAILS WHERE STD_NAME LIKE "%U";
SELECT ID,STD_NAME,STD_AGE FROM STD_DETAILS WHERE STD_NAME LIKE "_N%";

SELECT * FROM STD_DETAILS WHERE STD_SUB NOT IN(1,2,3);

SELECT * FROM STD_DETAILS;

SELECT * FROM STD_DETAILS WHERE STD_DOB BETWEEN "2001-01-01" AND "2003-01-01";
SELECT * FROM STD_DETAILS WHERE STD_AGE BETWEEN "20" AND "24"; 

SELECT ID AS ROLL_NO,STD_NAME AS NAME,STD_AGE AS AGE FROM STD_DETAILS;

SELECT * FROM STD_FEE;
SELECT * FROM STD_FEE ORDER BY AMOUNT DESC;
SELECT * FROM STD_FEE ORDER BY AMOUNT ASC;
SELECT DISTINCT(A_STATUS),COUNT(A_STATUS) FROM STD_FEE GROUP BY A_STATUS; 
SELECT * FROM STD_FEE WHERE A_STATUS="PAID" LIMIT 3;
SELECT * FROM STD_FEE WHERE A_STATUS="PAID" LIMIT 3 OFFSET 2;
SELECT MIN(AMOUNT) FROM STD_FEE;
SELECT MAX(AMOUNT) FROM STD_FEE;
SELECT AVG(AMOUNT) FROM STD_FEE;
SELECT COUNT(ID) FROM STD_FEE;
SELECT SUM(AMOUNT) FROM STD_FEE;

SELECT * FROM STD_DETAILS;
SELECT * FROM SUB_DETAILS;

SELECT * FROM STD_DETAILS INNER JOIN SUB_DETAILS ON STD_DETAILS.STD_SUB=SUB_DETAILS.SUB_ID;

SELECT * FROM STD_DETAILS LEFT JOIN SUB_DETAILS ON STD_DETAILS.STD_SUB=SUB_DETAILS.SUB_ID;

SELECT * FROM STD_DETAILS RIGHT JOIN SUB_DETAILS ON STD_DETAILS.STD_SUB=SUB_DETAILS.SUB_ID;

select std_details.std_name,sub_details.sub_name FROM STD_DETAILS LEFT OUTER JOIN SUB_DETAILS on
STD_DETAILS.STD_SUB=SUB_DETAILS.SUB_ID;

SELECT STD_DETAILS.STD_NAME,SUB_DETAILS.SUB_NAME FROM STD_DETAILS RIGHT OUTER JOIN SUB_DETAILS
ON STD_DETAILS.STD_SUB=SUB_DETAILS.SUB_ID;

SELECT * FROM STD_DETAILS CROSS JOIN STD_FEE;
SELECT * FROM STD_FEE;
SELECT A.STD_NAME,B.STD_NAME FROM STD_DETAILS A,STD_DETAILS B WHERE A.ID=B.ID;