CREATE DATABASE IF NOT EXISTS LibraryDB;
use LibraryDB;

# BOOKS TABLE
CREATE TABLE BOOKS(BOOK_ID INT AUTO_INCREMENT PRIMARY KEY,
TITLE VARCHAR(255) NOT NULL,
AUTHOR VARCHAR(255) NOT NULL,
GENRE VARCHAR(100),
PUBLISHED_YEAR YEAR,
IS_AVAILABLE BOOLEAN DEFAULT TRUE);

# MEMBERS TABLE
CREATE TABLE MEMBERS(MEMBER_ID INT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(255) NOT NULL,
EMAIL VARCHAR(255),
PHONE_NUMBER VARCHAR(15),
JOIN_DATE DATE DEFAULT (CURRENT_DATE)
);

#Librarians table
CREATE TABLE LIBRARIANS(LIBRARIAN_ID INT auto_increment primary KEY,
NAME VARCHAR(255) NOT NULL,
EMAIL VARCHAR(255),
PHONE_NUMBER VARCHAR(15),
HIRE_DATE DATE DEFAULT (CURRENT_DATE)
);

#BORROWING TABLE
CREATE TABLE BORROWING(LOAN_ID INT auto_increment PRIMARY KEY,
BOOK_ID INT,
MEMBER_ID INT,
BORROW_DATE DATE DEFAULT (CURRENT_DATE),
RETURN_DATE DATE,
LIBRARIAN_ID INT,
FOREIGN KEY(BOOK_ID) REFERENCES BOOKS(BOOK_ID),
FOREIGN KEY(MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID),
FOREIGN KEY(LIBRARIAN_ID) REFERENCES LIBRARIANS(lIBRARIAN_ID));




